### PR TITLE
Fix issue 46: add option to choose fork implementation

### PR DESCRIPTION
**Pull request by yanns**

### CODE REVIEW

**Comment by jrudolph** [comment]
Thanks, @yanns. We are currently in the process of wrapping up the first release of akka-http so we won't be able to publish a new version instantly. We'll have a look once that's done.

**Comment by yanns** [comment]
oh @jrudolph you just admitted that the release of sbt-revolver is not automated enough... :stuck_out_tongue_winking_eye: 

OK, I understand your priority, but please do not forget this issue. It is blocking the adoption of kamon.io.

**Comment by yanns** [comment]
Hi @jrudolph, what about a new release now?

**Comment by agourlay** [comment]
+1 for this PR.
We are hitting as well this bug with Kamon.

**Comment by jrudolph** [comment]
For now I've converted completely to `Fork.java` as that mirrors what `run` is doing (starting from the being published version 0.8.0-RC1). If the need should arise to make this configurable later on we can revive this PR. In any case, thanks for providing it, @yanns!

**Comment by yanns** [comment]
great news @jrudolph !

**Pull request closed without merging**
