### PR TITLE
Provide AutoPlugin support

### PR DESCRIPTION
**Pull request by alkersan**
Please, review this PR. It adds support of sbt.AutoPlugin. Primary concern - eliminate the need of any configuration in most cases.
So now only  ```addSbtPlugin("io.spray" % "sbt-revolver" % "0.7.3-SNAPSHOT")``` is needed to activate this plugin. Works for multi-module builds also.

### CODE REVIEW

**Comment by antonkulaga** [comment]
Is sbt-revolver alive?

**Comment by sirthias** [comment]
@antonkulaga Yes, it is.

Sorry for the delay in looking at this.
We are incredibly busy with finishing up Akka HTTP 1.0, which is why other things have had to suffer somewhat from attention deprivation.

To me this patch look like a good thing. @jrudolph ?

**Comment by jrudolph** [comment]
Yes, dropping support for older sbt versions is ok with me. I guess the real blocker on releasing a new version is that we need to update the publishing pipeline to publish to bintray which is not something I would want to do right now. As this doesn't add new functionality but just improves convenience I'd say we can postpone it for a few more weeks.

**Comment by antonkulaga** [comment]
Any progress in merging this?

**Comment by jrudolph** [comment]
I merged this locally and tried a local build but I'm currently stuck on sbt/sbt#1770 in my test project and I currently don't have any capacity to analyze what's going on.

**Pull request merged**
