### PR TITLE
Cross-build for SBT 1.0.0

### PR DESCRIPTION
**Pull request by liff**
Mainly to see how/if it works, I guess :)

Uses `crossSbtVersions` from SBT 0.13.16.

See also: #62.

### CODE REVIEW

**Comment by mielientiev** [comment]
@jrudolph when you can merge this PR?

**Comment by TimothyKlim** [comment]
@jrudolph any chance that this PR will be merged and released?

**Comment by jrudolph** [comment]
There seems to be some demand, so we'll try to get to this sometime this week.

**Comment by ngbinh** [comment]
+1 for this! Thanks

**Comment by liff** [comment]
Updated for 1.0.0-RC2, which seems to allow `src/main/scala-sbt-1.0` instead of the full binary version.

**Comment by jrudolph** [comment]
Thanks, @liff. It basically seems to work for me. It seems that color logging is lost in 1.0.0-RC2, do you have seen this as well? Did the behavior of `Logger.ansiCodesSupported` change?

**Comment by liff** [comment]
Didn't notice that, sorry. Looks like in 1.0.0-M6 and RC2 `ansiCodesSupported` is just `false`. A regression in SBT perhaps?

**Comment by liff** [comment]
@jrudolph reported sbt/sbt#3336

**Comment by jrudolph** [comment]
Thanks, I guess we might just ignore that for now and try to find out if that can be fixed in sbt.

**Comment by liff** [comment]
Updated. Color logging regression is fixed in 1.0.0-RC3.

**Comment by mielientiev** [comment]
@jrudolph I belive after @liff fix we can merge it. 
What do you think?

**Comment by martijnhoekstra** [comment]
@jrudolph just in case this escaped your attention and slipped through the cracks, there is hot demand, especially now that 1.0.0 final is out. A merge and release would be most appreciated

**Comment by jrudolph** [comment]
Thanks for notifying. We were just a bit delayed by summer vacations. We'll
make a release asap next week.

**Comment by jrudolph** [comment]
Thanks a lot, @liff. I tried it locally and it works perfectly.

**Pull request merged**
